### ISSUE TITLE
test_clip_dem_to_zones required temporary workaround for me

### ISSUE THREAD

**Issue by HEdingfield** [Geosyntec/python-tidegates#19]
The cause was the line `arcpy.management.Delete(raster)`. It had something to do with not being able to delete the file while it was being accessed by another program. I temporarily commented that out, and the test ran fine, but then I had to manually clean up the `_temp` and `info` folders and files in the testing directory. This might be resolved by putting that line at the end of the test?

**Comment by HEdingfield** [comment]
I'm now getting this traceback even if I do the previous override that worked:
```
Error
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.2\lib\unittest\case.py", line 327, in run
    testMethod()
  File "C:\Python27\ArcGIS10.2\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "H:\Dev\PyCharm Projects\python-tidegates\tidegates\tests\test_utils.py", line 348, in test_clip_dem_to_zones
    raster, result = utils.clip_dem_to_zones(demfile, zonefile)
  File "H:\Dev\PyCharm Projects\python-tidegates\tidegates\utils.py", line 161, in wrapper
    return func(*args, **kwargs)
  File "H:\Dev\PyCharm Projects\python-tidegates\tidegates\utils.py", line 355, in clip_dem_to_zones
    clipping_geometry="NONE",
  File "C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy\arcpy\management.py", line 12268, in Clip
    raise e
ExecuteError: ERROR 999999: Error executing function.
Failed to execute (Clip).
```

**Comment by phobson** [comment]
@HEdingfield can you spend some time trying to debug/fix this on your system?

**Comment by HEdingfield** [comment]
This issue resolved with latest pull from upstream.
